#!/usr/bin/env python
# Copyright (C) 2016 Cuckoo Foundation.
# This file is part of Cuckoo Sandbox - https://cuckoosandbox.org/.
# See the file 'docs/LICENSE' for copying permission.

import os
import setuptools
import sys

# Update the MANIFEST.in file to include the one monitor version that is
# actively shipped for this distribution and exclude all the other monitors
# that we have lying around. Note: I tried to do this is in a better manner
# through exclude_package_data, but without much luck.

excl, monitor = [], os.path.join("cuckoo", "data", "monitor")
latest = open(os.path.join(monitor, "latest"), "rb").read().strip()
for h in os.listdir(monitor):
    if h != "latest" and h != latest:
        excl.append(
            "recursive-exclude cuckoo/data/monitor/%s *  # AUTOGENERATED" % h
        )

if not os.path.isdir(os.path.join(monitor, latest)):
    sys.exit(
        "Failure locating the monitoring binaries that belong to the latest "
        "monitor release. Please include those to create a distribution."
    )

manifest = []
for line in open("MANIFEST.in", "rb"):
    if not line.strip() or "# AUTOGENERATED" in line:
        continue

    manifest.append(line.strip())

manifest.extend(excl)

open("MANIFEST.in", "wb").write("\n".join(manifest) + "\n")

setuptools.setup(
    name="Cuckoo",
    version="2.0",
    author="Jurriaan Bremer",
    author_email="jbr@cuckoo.sh",
    packages=[
        "cuckoo",
    ],
    url="https://cuckoosandbox.org/",
    license="GPLv3",
    description="Automated Malware Analysis System",
    include_package_data=True,
    entry_points={
        "console_scripts": [
            "cuckoo = cuckoo.main:main",
        ],
    },
    install_requires=[
        "alembic==0.8.0",
        "beautifulsoup4==4.4.1",
        "chardet==2.3.0",
        "click==6.6",
        "Django==1.8.4",
        "dpkt==1.8.7",
        "Flask==0.10.1",
        "HTTPReplay==0.1.15",
        "jsbeautifier==1.6.2",
        "lxml==3.6.0",
        "oletools==0.42",
        "peepdf==0.3.2",
        "pefile2==1.2.11",
        "pymisp==2.4.36",
        "pymongo==3.0.3",
        "python-dateutil==2.4.2",
        "python-magic==0.4.6",
        "requests[security]==2.7.0",
        "scapy==2.3.2",
        "SQLAlchemy==1.0.8",
        "wakeonlan==0.2.2",
    ],
    extras_require={
        "distributed": [
            "flask-sqlalchemy==2.1",
            "psycopg2==2.6.2",
        ],
    },
)
