# Copyright (C) 2012 Benjamin K., Kevin R., Claudio "nex" Guarnieri
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from lib.cuckoo.common.abstracts import Signature

class BuildLangID(Signature):
    name = "origin_langid"
    description = "Unconventional binary language"
    severity = 2
    authors = ["Benjamin K.", "Kevin R.", "nex", "RedSocks"]
    categories = ["origin"]
    minimum = "2.0"

    languages = [
        {"language": "Yiddish", "code": "0x043d"},
        {"language": "Vietnamese", "code": "0x042a"},
        {"language": "Tsonga", "code": "0x0431"},
        {"language": "Tamil", "code": "0x0449"},
        {"language": "Sorbian", "code": "0x042e"},
        {"language": "Sanskrit", "code": "0x044f"},
        {"language": "Russian (Moldova)", "code": "0x0819"},
        {"language": "Romanian (Moldova)", "code": "0x0818"},
        {"language": "Raeto-Romance", "code": "0x0417"},
        {"language": "Marathi", "code": "0x044e"},
        {"language": "Gaelic (Scotland)", "code": "0x043c"},
        {"language": "Gaelic (Ireland)", "code": "0x083c"},
        {"language": "Azeri (Latin)", "code": "0x042c"},
        {"language": "Azeri (Cyrillic)", "code": "0x082c"},
        {"language": "Portuguese (Brazil)", "code": "0x0416"},
        {"language": "Portuguese (Portugal)", "code": "0x0816"},
        {"language": "Armenian", "code": "0x042b"},
        {"language": "Quechua (Bolivia)", "code": "0x046b"},
        {"language": "Quechua (Ecuador)", "code": "0x086b"},
        {"language": "Quechua (Peru)", "code": "0x0c6b"},
        {"language": "Malay (Malaysian)", "code": "0x043e"},
        {"language": "Malay (Brunei Darussalam)", "code": "0x083e"},
        {"language": "Malayam (India)", "code": "0x044c"},
        {"language": "Maori (New Zealand)", "code": "0x0481"},
        {"language": "Maltese (Malta)", "code": "0x043a"},
        {"language": "Faroese", "code": "0x0438"},
        {"language": "Arabic (Saudi Arabia)", "code": "0x0401"},
        {"language": "Arabic (Iraq)", "code": "0x0801"},
        {"language": "Arabic (Egypt)", "code": "0x0c01"},
        {"language": "Arabic (Libya)", "code": "0x1001"},
        {"language": "Arabic (Algeria)", "code": "0x1401"},
        {"language": "Arabic (Morocco)", "code": "0x1801"},
        {"language": "Arabic (Tunisia)", "code": "0x1c01"},
        {"language": "Arabic (Oman)", "code": "0x2001"},
        {"language": "Arabic (Yemen)", "code": "0x2401"},
        {"language": "Arabic (Syria)", "code": "0x2801"},
        {"language": "Arabic (Jordan)", "code": "0x2c01"},
        {"language": "Arabic (Lebanon)", "code": "0x3001"},
        {"language": "Arabic (Kuwait)", "code": "0x3401"},
        {"language": "Arabic (U.A.E.)", "code": "0x3801"},
        {"language": "Arabic (Bahrain)", "code": "0x3c01"},
        {"language": "Arabic (Qatar)", "code": "0x4001"},
        {"language": "Basque", "code": "0x042d"},
        {"language": "Uzbek (Latin)", "code": "0x0443"},
        {"language": "Welsh (United Kingdom)", "code": "0x0452"},
        {"language": "Uzbek (Cyrillic)", "code": "0x0843"},
        {"language": "Croatian", "code": "0x041a"},
        {"language": "Serbian (Cyrillic)", "code": "0x0c1a"},
        {"language": "Serbian (Cyrillic, Bosnia and Herzegovina)", "code": "0x1c1a"},
        {"language": "Serbian (Latin)", "code": "0x081a"},
        {"language": "Serbian (Latin, Bosnia and Herzegovina)", "code": "0x181a"},
        {"language": "Sami, Northern (Norway)", "code": "0x043b"},
        {"language": "Sami, Northern (Sweden)", "code": "0x083b"},
        {"language": "Sami, Northern (Finland)", "code": "0x0c3b"},
        {"language": "Sami, Lule (Norway)", "code": "0x103b"},
        {"language": "Sami, Lule (Sweden)", "code": "0x143b"},
        {"language": "Sami, Southern (Norway)", "code": "0x183b"},
        {"language": "Sami, Southern (Sweden)", "code": "0x1c3b"},
        {"language": "Sami, Skolt (Finland)", "code": "0x203b"},
        {"language": "Sami, Inari (Finland)", "code": "0x243b"},
        {"language": "Finnish", "code": "0x040b"},
        {"language": "Urdu (India)", "code": "0x0820"},
        {"language": "Farsi", "code": "0x0429"},
        {"language": "French", "code": "0x040c"},
        {"language": "French (Belgian)", "code": "0x080c"},
        {"language": "French (Canadian)", "code": "0x0c0c"},
        {"language": "French (Switzerland)", "code": "0x100c"},
        {"language": "German (Austria)", "code": "0x0c07"},
        {"language": "French (Luxembourg)", "code": "0x140c"},
        {"language": "French (Monaco)", "code": "0x180c"},
        {"language": "Slovenian", "code": "0x0424"},
        {"language": "Spanish (Traditional)", "code": "0x040a"},
        {"language": "Spanish (Mexican)", "code": "0x080a"},
        {"language": "Spanish (Modern)", "code": "0x0c0a"},
        {"language": "Spanish (Guatemala)", "code": "0x100a"},
        {"language": "Spanish (Costa Rica)", "code": "0x140a"},
        {"language": "Spanish (Panama)", "code": "0x180a"},
        {"language": "Spanish (Dominican Republic)", "code": "0x1c0a"},
        {"language": "Spanish (Venezuela)", "code": "0x200a"},
        {"language": "Spanish (Colombia)", "code": "0x240a"},
        {"language": "Spanish (Peru)", "code": "0x280a"},
        {"language": "Spanish (Argentina)", "code": "0x2c0a"},
        {"language": "Spanish (Ecuador)", "code": "0x300a"},
        {"language": "Spanish (Chile)", "code": "0x340a"},
        {"language": "Spanish (Uruguay)", "code": "0x3840a"},
        {"language": "Spanish (Paraguay)", "code": "0x3c0a"},
        {"language": "Spanish (Bolivia)", "code": "0x400a"},
        {"language": "Spanish (El Salvador)", "code": "0x440a"},
        {"language": "Spanish (Honduras)", "code": "0x480a"},
        {"language": "Spanish (Nicaragua)", "code": "0x4c0a"},
        {"language": "Spanish (Puerto Rico)", "code": "0x500a"},
        {"language": "Sutu", "code": "0x0430"},
        {"language": "Swahili (Kenya)", "code": "0x0441"},
        {"language": "Swedish", "code": "0x041d"},
        {"language": "Tatar (Tatarstan)", "code": "0x0444"},
        {"language": "Swedish (Finland)", "code": "0x081d"},
        {"language": "Thai", "code": "0x041e"},
        {"language": "Estonian", "code": "0x0425"},
        {"language": "Latvian", "code": "0x0426"},
        {"language": "Macedonian", "code": "0x042f"},
        {"language": "Lithuanian", "code": "0x0427"},
        {"language": "Faeroese", "code": "0x0438"},
        {"language": "Gujarati", "code": "0x0447"},
        {"language": "Japanese", "code": "0x0411"},
        {"language": "Catalan", "code": "0x0403"},
        {"language": "Czech", "code": "0x0405"},
        {"language": "Danish", "code": "0x0406"},
        {"language": "Dutch", "code": "0x0413"},
        {"language": "Dutch (Belgium)", "code": "0x0813"},
        {"language": "English (Australia)", "code": "0x0c09"},
        # {"language": "English (New Zealand)", "code": "0x1409"},
        # {"language": "English (United States)", "code": "0x0409"},
        {"language": "English (United Kingdom)", "code": "0x0809"},
        {"language": "English (Ireland)", "code": "0x1809"},
        {"language": "English (Canada)", "code": "0x1009"},
        {"language": "English (South Africa)", "code": "0x1c09"},
        {"language": "Setswana/Tswana (South Africa)", "code": "0x0432"},
        {"language": "Sesotho sa Leboa / Northern Soto (South Africa)", "code": "0x046c"},
        {"language": "Xhosa (South Africa)", "code": "0x0434"},
        {"language": "Afrikaans (South Africa)", "code": "0x0436"},
        {"language": "Zulu (South Africa)", "code": "0x0435"},
        {"language": "English (Jamaica)", "code": "0x2009"},
        {"language": "English (Caribbean)", "code": "0x2409"},
        {"language": "English (Belize)", "code": "0x2809"},
        {"language": "English (Trinidad)", "code": "0x2c09"},
        {"language": "English (Zimbabwe)", "code": "0x3009"},
        {"language": "English (Philippines)", "code": "0x3409"},
        {"language": "German", "code": "0x0407"},
        {"language": "German (Liechtenstein)", "code": "0x1407"},
        {"language": "German (Switzerland)", "code": "0x0807"},
        {"language": "German (Luxembourg)", "code": "0x1007"},
        {"language": "Greek", "code": "0x0408"},
        {"language": "Indonesian", "code": "0x0421"},
        {"language": "Italian", "code": "0x0410"},
        {"language": "Italian (Switzerland)", "code": "0x0810"},
        {"language": "Korean", "code": "0x0412"},
        {"language": "Norwegian (Bokmal)", "code": "0x0414"},
        {"language": "Norwegian (Nynorsk)", "code": "0x0814"},
        {"language": "Polish", "code": "0x0415"},
        {"language": "Bulgarian", "code": "0x0402"},
        {"language": "Traditional Chinese", "code": "0x0404"},
        {"language": "Chinese (Macau)", "code": "0x1404"},
        {"language": "Chinese (Hong Kong)", "code": "0x0c04"},
        {"language": "Chinese (Singapore)", "code": "0x1004"},
        {"language": "Romanian", "code": "0x0418"},
        {"language": "Russian", "code": "0x0419"},
        {"language": "Belarussian", "code": "0x0423"},
        {"language": "Ukrainian", "code": "0x0422"},
        {"language": "Bengali (India)", "code": "0x0445"},
        {"language": "Croato-Serbian", "code": "0x041a"},
        {"language": "Croatian (Bosnia and Herzegovina)", "code": "0x101a"},
        {"language": "Slovak", "code": "0x041b"},
        {"language": "Albanian", "code": "0x041c"},
        {"language": "Turkish", "code": "0x041f"},
        {"language": "Bosnian", "code": "0x141a"},
        {"language": "Burmese", "code": "0x0455"},
        {"language": "Simplified Chinese", "code": "0x0804"},
        {"language": "Hindi", "code": "0x0439"},
        {"language": "Icelandic", "code": "0x040f"},
        {"language": "Hungarian", "code": "0x040e"},
        {"language": "Hebrew", "code": "0x040d"},
    ]

    def on_complete(self):
        for info in self.get_results("static", {}).get("pe_versioninfo", []):
            if info["name"] != "Translation":
                continue

            lang, charset = info["value"].strip().split(" ")
            for language in self.languages:
                if language["code"] == lang:
                    self.mark(language=language["language"],
                              description="A foreign language has been detected")
