# Copyright (C) 2010-2013 Cuckoo Sandbox Developers.
# This file is part of Cuckoo Sandbox - http://www.cuckoosandbox.org
# See the file "docs/LICENSE" for copying permission.

api_call_mappings = {
"NtCreateFile" : {"action_name" : "create file",
				          "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
				          "parameter_associated_objects" : {"FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				  													                                "associated_object_element" : "ID",
																	                                  "association_type" : "output"},
													                          "FileName" : {"associated_object_type" : "FileObjectType",
												   				                                "associated_object_element" : "File_Path",
												   				                                "association_type" : "output"}}},				  								   	
"NtOpenFile" : {"action_name" : "open file",
                "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
                "parameter_associated_objects" : {"FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "output"},
                                                  "FileName" : {"associated_object_type" : "FileObjectType",
                                                                "associated_object_element" : "File_Path",
                                                                "association_type" : "input"}}},
"NtReadFile" : {"action_name" : "read from file",
				"action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
				"parameter_associated_objects" : {"FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																  "associated_object_element" : "ID",
																  "association_type" : "input"}}},
"NtWriteFile" : {"action_name" : "write to file",
				 "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
				 "parameter_associated_objects" : {"FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				 												   "associated_object_element" : "ID",
				 												   "association_type" : "input"}}},
"NtDeleteFile" : {"action_name" : "delete file",
				  "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
				  "parameter_associated_objects" : {"FileName" : {"associated_object_type" : "FileObjectType",
				  												  "associated_object_element" : "File_Path",
				  												  "association_type" : "input"}}},
"NtDeviceIoControlFile" : {"action_name" : "send control code to file",
						   "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
						   "parameter_associated_objects" : {"FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						   													 "associated_object_element" : "ID",
						   													 "association_type" : "input"}}},
"NtQueryDirectoryFile" : {"action_name" : "find file",
						  "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
						  "parameter_associated_objects" : {"FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						  												    "associated_object_element" : "ID",
						  												    "association_type" : "input"},
						  									"FileName" : {"associated_object_type" : "FileObjectType",
						  												  "associated_object_element" : "File_Path",
						  												  "association_type" : "input"}}},
"NtQueryInformationFile" : {"action_name" : "get file attributes",
							"action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
							"parameter_associated_objects" : {"FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																			  "associated_object_element" : "ID",
																			  "association_type" : "input"}}},
"NtSetInformationFile" : {"action_name" : "set file attributes",
						  "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
						  "parameter_associated_objects" : {"FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																			"associated_object_element" : "ID",
																			"association_type" : "input"}}},
"NtCreateDirectoryObject" : {"action_name" : "create directory",
							 "action_vocab" : "maecVocabs:DirectoryActionNameVocab-1.0",
							 "parameter_associated_objects" : {"DirectoryHandle" : {"associated_object_type" : "WindowsHandleObjectType",
							 														"associated_object_element" : "ID",
							 														"association_type" : "output"}}},
"CreateDirectoryW" : {"action_name" : "create directory",
					  "action_vocab" : "maecVocabs:DirectoryActionNameVocab-1.0",
					  "parameter_associated_objects" : {"DirectoryName" : {"associated_object_type" : "FileObjectType",
					  													   "associated_object_element" : "File_Path",
					  													   "association_type" : "output"}}},
"CreateDirectoryExW" : {"action_name" : "create directory",
					  	"action_vocab" : "maecVocabs:DirectoryActionNameVocab-1.0",
					  	"parameter_associated_objects" : {"DirectoryName" : {"associated_object_type" : "FileObjectType",
					  													   	 "associated_object_element" : "File_Path",
					  													   	 "association_type" : "output"}}},
"RemoveDirectoryA" : {"action_name" : "delete directory",
					  "action_vocab" : "maecVocabs:DirectoryActionNameVocab-1.0",
					  "parameter_associated_objects" : {"DirectoryName" : {"associated_object_type" : "FileObjectType",
					  													   "associated_object_element" : "File_Path",
					  													   "association_type" : "input"}}},
"RemoveDirectoryW" : {"action_name" : "delete directory",
					  "action_vocab" : "maecVocabs:DirectoryActionNameVocab-1.0",
					  "parameter_associated_objects" : {"DirectoryName" : {"associated_object_type" : "FileObjectType",
					  													   "associated_object_element" : "File_Path",
					  													   "association_type" : "input"}}},
"MoveFileWithProgressW" : {"action_name" : "move file",
						   "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
						   "parameter_associated_objects" : {"ExistingFileName" : {"associated_object_type" : "FileObjectType",
						   														   "associated_object_element" : "File_Path",
						   														   "association_type" : "input"},
						   									 "NewFileName" : {"associated_object_type" : "FileObjectType",
						   									 				  "associated_object_element" : "File_Path",
						   									 				  "association_type" : "output"}}},
"FindFirstFileExA" : {"action_name" : "find file",
					  "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
					  "parameter_associated_objects" : {"FileName" : {"associated_object_type" : "FileObjectType",
					  												  "associated_object_element" : "File_Path",
					  												  "association_type" : "input"}}},
"FindFirstFileExW" : {"action_name" : "find file",
					  "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
					  "parameter_associated_objects" : {"FileName" : {"associated_object_type" : "FileObjectType",
					  												  "associated_object_element" : "File_Path",
					  												  "association_type" : "input"}}},
"CopyFileA" : {"action_name" : "copy file",
			   "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
			   "parameter_associated_objects" : {"ExistingFileName" : {"associated_object_type" : "FileObjectType",
			   														   "associated_object_element" : "File_Path",
			   														   "association_type" : "input"},
			   									 "NewFileName" : {"associated_object_type" : "FileObjectType",
			   									 				  "associated_object_element" : "File_Path",
			   									 				  "association_type" : "output"}}},
"CopyFileW" : {"action_name" : "copy file",
			   "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
			   "parameter_associated_objects" : {"ExistingFileName" : {"associated_object_type" : "FileObjectType",
			   														   "associated_object_element" : "File_Path",
			   														   "association_type" : "input"},
			   									 "NewFileName" : {"associated_object_type" : "FileObjectType",
			   									 				  "associated_object_element" : "File_Path",
			   									 				  "association_type" : "output"}}},
"CopyFileExW" : {"action_name" : "copy file",
			   	 "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
			   	 "parameter_associated_objects" : {"ExistingFileName" : {"associated_object_type" : "FileObjectType",
			   															 "associated_object_element" : "File_Path",
			   															 "association_type" : "input"},
			   									   "NewFileName" : {"associated_object_type" : "FileObjectType",
			   									 				  	"associated_object_element" : "File_Path",
			   									 				  	"association_type" : "output"}}},
"DeleteFileA" : {"action_name" : "delete file",
				 "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
				 "parameter_associated_objects" : {"FileName" : {"associated_object_type" : "FileObjectType",
				 												 "associated_object_element" : "File_Path",
				 												 "association_type" : "input"}}},
"DeleteFileW" : {"action_name" : "delete file",
				 "action_vocab" : "maecVocabs:FileActionNameVocab-1.0",
				 "parameter_associated_objects" : {"FileName" : {"associated_object_type" : "FileObjectType",
				 												 "associated_object_element" : "File_Path",
				 												 "association_type" : "input"}}},
"RegOpenKeyExA" : {"action_name" : "open registry key",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"Registry" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                   "associated_object_element" : "Hive",
                                                                   "association_type" : "input",
                                                                   "post_processing" : "hiveHexToString"},
                                                     "Subkey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                 "associated_object_element" : "Key",
                                                                 "association_type" : "input",},
                                                     "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "output"},
                                                     "group_together" : ["Registry", "Subkey"]}},
"RegOpenKeyExA" : {"action_name" : "open registry key",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"Registry" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                   "associated_object_element" : "Hive",
                                                                   "association_type" : "input",
                                                                   "post_processing" : "hiveHexToString"},
                                                     "Subkey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                 "associated_object_element" : "Key",
                                                                 "association_type" : "input",},
                                                     "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "output"},
                                                     "group_together" : ["Registry", "Subkey"]}},
"RegOpenKeyExW" : {"action_name" : "open registry key",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"Registry" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                   "associated_object_element" : "Hive",
                                                                   "association_type" : "input",
                                                                   "post_processing" : "hiveHexToString"},
                                                     "Subkey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                 "associated_object_element" : "Key",
                                                                 "association_type" : "input",},
                                                     "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "output"},
                                                     "group_together" : ["Registry", "Subkey"]}},
"RegCreateKeyExA" : {"action_name" : "create registry key",
                     "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                     "parameter_associated_objects" : {"Registry" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                   "associated_object_element" : "Hive",
                                                                   "association_type" : "output",
                                                                   "post_processing" : "hiveHexToString"},
                                                     "Subkey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                 "associated_object_element" : "Key",
                                                                 "association_type" : "output"},
                                                     "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "output"},
                                                     "group_together" : ["Registry", "Subkey"]}},
"RegCreateKeyExW" : {"action_name" : "create registry key",
                     "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                     "parameter_associated_objects" : {"Registry" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                   "associated_object_element" : "Hive",
                                                                   "association_type" : "output",
                                                                   "post_processing" : "hiveHexToString"},
                                                     "Subkey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                 "associated_object_element" : "Key",
                                                                 "association_type" : "output"},
                                                     "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "output"},
                                                     "group_together" : ["Registry", "Subkey"]}},
"RegDeleteKeyA" : {"action_name" : "delete registry key",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"Subkey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                 "associated_object_element" : "Key",
                                                                 "association_type" : "input"},
                                                     "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "input"}}},
"RegDeleteKeyW" : {"action_name" : "delete registry key",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"Subkey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                 "associated_object_element" : "Key",
                                                                 "association_type" : "input"},
                                                     "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "input"}}},
"RegEnumKeyW" : {"action_name" : "enumerate registry key subkeys",
                 "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                 "parameter_associated_objects" : {"Name" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                            "associated_object_element" : "Key",
                                                            "association_type" : "output"},
                                                  "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                              "associated_object_element" : "ID",
                                                              "association_type" : "input"}}},
"RegEnumKeyExA" : {"action_name" : "enumerate registry key subkeys",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"Name" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                              "associated_object_element" : "Key",
                                                              "association_type" : "output"},
                                                    "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                "associated_object_element" : "ID",
                                                                "association_type" : "input"}}},
"RegEnumKeyExW" : {"action_name" : "enumerate registry key subkeys",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"Name" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                              "associated_object_element" : "Key",
                                                              "association_type" : "output"},
                                                    "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                "associated_object_element" : "ID",
                                                                "association_type" : "input"}}},
"RegEnumValueA" : {"action_name" : "enumerate registry key values",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Name",
                                                                    "association_type" : "output"},
                                                    "Type" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Datatype",
                                                                    "association_type" : "output"},
                                                    "Data" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Data",
                                                                    "association_type" : "output"},
                                                    "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                "associated_object_element" : "ID",
                                                                "association_type" : "input"},
                                                    "group_together" : ["ValueName", "Type", "Data"]}},
"RegEnumValueW" : {"action_name" : "enumerate registry key values",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Name",
                                                                    "association_type" : "output"},
                                                    "Type" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Datatype",
                                                                    "association_type" : "output"},
                                                    "Data" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Data",
                                                                    "association_type" : "output"},
                                                    "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                "associated_object_element" : "ID",
                                                                "association_type" : "input"},
                                                    "group_together" : ["ValueName", "Type", "Data"]}},
"RegSetValueExA" : {"action_name" : "modify registry key value",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Name",
                                                                    "association_type" : "output"},
                                                    "Type" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Datatype",
                                                                    "association_type" : "output"},
                                                    "Buffer" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Data",
                                                                    "association_type" : "output"},
                                                    "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                "associated_object_element" : "ID",
                                                                "association_type" : "input"},
                                                    "group_together" : ["ValueName", "Type", "Buffer"]}},
"RegSetValueExW" : {"action_name" : "modify registry key value",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Name",
                                                                    "association_type" : "output"},
                                                    "Type" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Datatype",
                                                                    "association_type" : "output"},
                                                    "Buffer" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Data",
                                                                    "association_type" : "output"},
                                                    "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                "associated_object_element" : "ID",
                                                                "association_type" : "input"},
                                                    "group_together" : ["ValueName", "Type", "Buffer"]}},
"RegQueryValueExA" : {"action_name" : "read registry key value",
                      "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                      "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                       "associated_object_element" : "Values/list__Name",
                                                                       "association_type" : "input"},
                                                        "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                    "associated_object_element" : "ID",
                                                                    "association_type" : "input"},
                                                        "group_together_nested" : {"parameter_mappings" : [{"parameter_name" : "Type", "element_name" : "Datatype"},
                                                                                                           {"parameter_name" : "Data", "element_name" : "Data"}],
                                                                                   "associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                                   "associated_object_element" : "Values/list__",
                                                                                   "association_type" : "output"}}},
"RegQueryValueExW" : {"action_name" : "read registry key value",
                      "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                      "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                       "associated_object_element" : "Values/list__Name",
                                                                       "association_type" : "input"},
                                                        "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                    "associated_object_element" : "ID",
                                                                    "association_type" : "input"},
                                                        "group_together_nested" : {"parameter_mappings" : [{"parameter_name" : "Type", "element_name" : "Datatype"},
                                                                                                           {"parameter_name" : "Data", "element_name" : "Data"}],
                                                                                   "associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                                   "associated_object_element" : "Values/list__",
                                                                                   "association_type" : "output"}}},
"RegDeleteValueA" : {"action_name" : "delete registry key value",
                     "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                     "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                       "associated_object_element" : "Values/list__Name",
                                                                       "association_type" : "input"},
                                                        "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                    "associated_object_element" : "ID",
                                                                    "association_type" : "input"}}},
"RegDeleteValueW" : {"action_name" : "delete registry key value",
                     "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                     "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                       "associated_object_element" : "Values/list__Name",
                                                                       "association_type" : "input"},
                                                        "Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                    "associated_object_element" : "ID",
                                                                    "association_type" : "input"}}},
"RegQueryInfoKeyA" : {"action_name" : "get registry key attributes",
                     "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                     "parameter_associated_objects" : {"KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                    "associated_object_element" : "ID",
                                                                    "association_type" : "input"}}},
"RegQueryInfoKeyW" : {"action_name" : "get registry key attributes",
                     "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                     "parameter_associated_objects" : {"KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                    "associated_object_element" : "ID",
                                                                    "association_type" : "input"}}},
"RegCloseKey" : {"action_name" : "close registry key",
                 "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                 "parameter_associated_objects" : {"Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                    "associated_object_element" : "ID",
                                                                    "association_type" : "input"}}},
"NtCreateKey" : {"action_name" : "create registry key",
                 "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                 "parameter_associated_objects" : {"ObjectAttributes" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                         "associated_object_element" : "Key",
                                                                         "association_type" : "output"},
                                                   "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "output"}}},
"NtOpenKey" : {"action_name" : "open registry key",
               "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
               "parameter_associated_objects" : {"ObjectAttributes" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                       "associated_object_element" : "Key",
                                                                       "association_type" : "input"},
                                                  "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                 "associated_object_element" : "ID",
                                                                 "association_type" : "output"}}},
"NtOpenKeyEx" : {"action_name" : "open registry key",
               "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
               "parameter_associated_objects" : {"ObjectAttributes" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                       "associated_object_element" : "Key",
                                                                       "association_type" : "input"},
                                                  "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                 "associated_object_element" : "ID",
                                                                 "association_type" : "output"}}},
"NtRenameKey" : {"action_name" : "rename registry key",
                 "parameter_associated_objects" : {"NewName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                "associated_object_element" : "Key",
                                                                "association_type" : "input"},
                                                  "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                 "associated_object_element" : "ID",
                                                                 "association_type" : "input"}}},
"NtReplaceKey" : {"action_name" : "save hive key to file",
                  "parameter_associated_objects" : {"NewHiveFileName" : {"associated_object_type" : "FileObjectType",
                                                                         "associated_object_element" : "File_Path",
                                                                         "association_type" : "output"},
                                                  "OldHiveFileName" : {"associated_object_type" : "FileObjectType",
                                                                       "associated_object_element" : "File_Path",
                                                                       "association_type" : "output"},
                                                  "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                 "associated_object_element" : "ID",
                                                                 "association_type" : "input"}}},
"NtEnumerateKey" : {"action_name" : "enumerate registry key subkeys",
                    "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                    "parameter_associated_objects" : {"KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                              "associated_object_element" : "ID",
                                                              "association_type" : "input"}}},
"NtEnumerateKeyValue" : {"action_name" : "enumerate registry key values",
                         "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                         "parameter_associated_objects" : {"KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                          "associated_object_element" : "ID",
                                                                          "association_type" : "input"}}},
"NtSetValueKey" : {"action_name" : "modify registry key value",
                   "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                   "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                    "associated_object_element" : "Values/list__Name",
                                                                    "association_type" : "output"},
                                                    "Type" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                              "associated_object_element" : "Values/list__Datatype",
                                                              "association_type" : "output"},
                                                    "Buffer" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                "associated_object_element" : "Values/list__Data",
                                                                "association_type" : "output"},
                                                    "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                   "associated_object_element" : "ID",
                                                                   "association_type" : "input"},
                                                    "group_together" : ["ValueName", "Type", "Buffer"]}},
"NtQueryValueKey" : {"action_name" : "read registry key value",
                     "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                     "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                      "associated_object_element" : "Values/list__Name",
                                                                      "association_type" : "input"},
                                                        "Type" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                  "associated_object_element" : "Values/list__Datatype",
                                                                  "association_type" : "output"},
                                                        "Information" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                         "associated_object_element" : "Values/list__Data",
                                                                         "association_type" : "output"},
                                                        "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                       "associated_object_element" : "ID",
                                                                       "association_type" : "input"},
                                                        "group_together" : ["Type", "ValueName"]}},
"NtQueryMultipleValueKey" : {"action_name" : "read registry key value",
                             "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                             "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                              "associated_object_element" : "Values/list__Name",
                                                                              "association_type" : "input"},
                                                               "ValueBuffer" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                                "associated_object_element" : "Values/list__Data",
                                                                                "association_type" : "output"},
                                                               "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                              "associated_object_element" : "ID",
                                                                              "association_type" : "input"}}},
"NtDeleteKey" : {"action_name" : "delete registry key",
                 "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                 "parameter_associated_objects" : {"KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "input"}}},
"NtDeleteValueKey" : {"action_name" : "delete registry key value",
                      "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                      "parameter_associated_objects" : {"ValueName" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                       "associated_object_element" : "Values/list__Name",
                                                                       "association_type" : "input"},
                                                        "KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                       "associated_object_element" : "ID",
                                                                       "association_type" : "input"}}},
"NtLoadKey" : {"action_name" : "load registry keys from file",
               "parameter_associated_objects" : {"TargetKey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                "associated_object_element" : "Key",
                                                                "association_type" : "input"},
                                                 "SourceFile" : {"associated_object_type" : "FileObjectType",
                                                                 "associated_object_element" : "File_Path",
                                                                 "association_type" : "input"}}},
"NtLoadKey2" : {"action_name" : "load registry keys from file",
                "parameter_associated_objects" : {"TargetKey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                 "associated_object_element" : "Key",
                                                                 "association_type" : "input"},
                                                 "SourceFile" : {"associated_object_type" : "FileObjectType",
                                                                 "associated_object_element" : "File_Path",
                                                                 "association_type" : "input"}}},
"NtLoadKeyEx" : {"action_name" : "load registry keys from file",
                 "parameter_associated_objects" : {"TargetKey" : {"associated_object_type" : "WindowsRegistryKeyObjectType",
                                                                  "associated_object_element" : "Key",
                                                                  "association_type" : "input"},
                                                  "SourceFile" : {"associated_object_type" : "FileObjectType",
                                                                  "associated_object_element" : "File_Path",
                                                                  "association_type" : "input"}}},
"NtQueryKey" : {"action_name" : "get registry key attributes",
                "action_vocab" : "maecVocabs:RegistryActionNameVocab-1.0",
                "parameter_associated_objects" : {"Handle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                              "associated_object_element" : "ID",
                                                              "association_type" : "input"}}},
"NtSaveKey" : {"action_name" : "save registry key subtree to file",
               "parameter_associated_objects" : {"KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                "associated_object_element" : "ID",
                                                                "association_type" : "input"},
                                                 "FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                 "associated_object_element" : "ID",
                                                                 "association_type" : "input"}}},
"NtSaveKeyEx" : {"action_name" : "save registry key subtree to file",
                 "parameter_associated_objects" : {"KeyHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                  "associated_object_element" : "ID",
                                                                  "association_type" : "input"},
                                                   "FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
                                                                   "associated_object_element" : "ID",
                                                                   "association_type" : "input"}}},                                                                                                                                                  
"NtCreateProcess" : {"action_name" : "create process",
					 "action_vocab" : "maecVocabs:ProcessActionNameVocab-1.0",
					  "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
					 													   "associated_object_element" : "ID",
					 													   "association_type" : "output"},
					 								  "FileName" : {"associated_object_type" : "FileObjectType",
					 								  				"associated_object_element" : "File_Path",
					 								  				"association_type" : "input"}}},
"NtCreateProcessEx" : {"action_name" : "create process",
					   "action_vocab" : "maecVocabs:ProcessActionNameVocab-1.0",
					   "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
					 													 	"associated_object_element" : "ID",
					 													 	"association_type" : "output"},
					 								  "FileName" : {"associated_object_type" : "FileObjectType",
					 								  				"associated_object_element" : "File_Path",
					 								  				"association_type" : "input"}}},
"NtCreateUserProcess" : {"action_name" : "create process",
					 	 "action_vocab" : "maecVocabs:ProcessActionNameVocab-1.0",
					  	 "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
					 													   "associated_object_element" : "ID",
					 													   "association_type" : "output"},
					 										"ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
					 														  "associated_object_element" : "ID",
					 														  "association_type" : "output"},
					 										"ProcessFileName" : {"associated_object_type" : "FileObjectType",
					 															 "associated_object_element" : "File_Path",
					 															 "association_type" : "input"},
					 										"ThreadName" : {"associated_object_type" : "WindowsThreadObjectType",
					 														"associated_object_element" : "Thread_ID",
					 														"association_type" : "input"},
					 								  		"ImagePathName" : {"associated_object_type" : "ProcessObjectType",
					 								  						   "associated_object_element" : "Image_Info/Path",
					 								  						   "association_type" : "input"}}},
"NtOpenProcess" : {"action_name" : "open process",
				   "action_vocab" : "maecVocabs:ProcessActionNameVocab-1.0",
				   "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				   														"associated_object_element" : "ID",
				   														"association_type" : "output"},
				   									 "ProcessIdentifier" : {"associated_object_type" : "ProcessObjectType",
				   									 						"associated_object_element" : "PID",
				   									 						"association_type" : "input"}}},
"NtTerminateProcess" : {"action_name" : "kill process",
				   		"action_vocab" : "maecVocabs:ProcessActionNameVocab-1.0",
				   		"parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				   															 "associated_object_element" : "ID",
				   															 "association_type" : "input"}}},
"NtCreateSection" : {"action_name" : "create section",
					 "parameter_associated_objects" : {"SectionHandle" : {"associated_object_type" : "WindowsHandleObjectType",
					 													  "associated_object_element" : "ID",
					 													  "association_type" : "output"},
					 								   "FileHandle" : {"associated_object_type" : "WindowsHandleObjectType",
					 								   				   "associated_object_element" : "ID",
					 								   				   "association_type" : "input"}}}, 
"NtOpenSection" : {"action_name" : "open section",
				   "parameter_associated_objects" : {"SectionHandle" : {"associated_object_type" : "WindowsHandleObjectType",
					 													  "associated_object_element" : "ID",
					 													  "association_type" : "output"}}},
"CreateProcessInternalW" : {"action_name" : "create process",
					 	 	"action_vocab" : "maecVocabs:ProcessActionNameVocab-1.0",
					  	 	"parameter_associated_objects" : {"ApplicationName" : {"associated_object_type" : "",
					  	 														   "associated_object_element" : "",
					  	 														   "association_type" : "input"},
					  	 									  "ProcessId" : {"associated_object_type" : "WindowsProcessObjectType",
					  	 									  			 	 "associated_object_element" : "PID",
					  	 									  			 	 "association_type" : "output"},
					  	 									  "ThreadId" : {"associated_object_type" : "WindowsThreadObjectType",
					  	 									  				"associated_object_element" : "Thread_ID",
					  	 									  				"association_type" : "output"},
					  	 									  "ProcessHandle" : {"associated_object_type" : "WindowsProcessObjectType",
					 													   		 "associated_object_element" : "Handle_List/list__ID",
					 													   		 "association_type" : "output"},
					 										  "ThreadHandle" : {"associated_object_type" : "WindowsThreadObjectType",
					 														  "associated_object_element" : "Handle",
					 														  "association_type" : "output"}}},
"ShellExecuteExW" : {"action_name" : "create process",
					 "action_vocab" : "maecVocabs:ProcessActionNameVocab-1.0",
					 "parameter_associated_objects" : {"FilePath" : {"associated_object_type" : "FileObjectType",
					 												 "associated_object_element" : "File_Path",
					 												 "association_type" : "input" }}},
"NtAllocateVirtualMemory" : {"action_name" : "allocate process virtual memory",
							 "action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
							 "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
							 													  "associated_object_element" : "ID",
							 													  "association_type" : "input"}}},
"NtReadVirtualMemory" : {"action_name" : "read from process memory",
						 "action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
						 "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						 													  "associated_object_element" : "ID",
						 													  "association_type" : "input"}}},
"ReadProcessMemory" : {"action_name" : "read from process memory",
					   "action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
					   "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						 													"associated_object_element" : "ID",
						 													"association_type" : "input"}}},
"NtWriteVirtualMemory" : {"action_name" : "write to process memory",
						 "action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
						 "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						 													  "associated_object_element" : "ID",
						 													  "association_type" : "input"}}},
"WriteProcessMemory" : {"action_name" : "write to process memory",
						"action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
						"parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						 													 "associated_object_element" : "ID",
						 													 "association_type" : "input"}}},
"NtProtectVirtualMemory" : {"action_name" : "modify process virtual memory protection",
						 	"action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
						 	"parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						 													  	 "associated_object_element" : "ID",
						 													  	 "association_type" : "input"}}},
"VirtualProtectEx" : {"action_name" : "modify process virtual memory protection",
					  "action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
					  "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																	  	   "associated_object_element" : "ID",
						 												   "association_type" : "input"}}},
"NtFreeVirtualMemory" : {"action_name" : "free process virtual memory",
						 "action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
						 "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						 													  "associated_object_element" : "ID",
						 													  "association_type" : "input"}}},
"VirtualFreeEx" : {"action_name" : "free process virtual memory",
				   "action_vocab" : "maecVocabs:ProcessMemoryActionNameVocab-1.0",
				   "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
						 												"associated_object_element" : "ID",
						 												"association_type" : "input"}}},
"FindWindowA" : {"action_name" : "find window",
				 "action_vocab" : "maecVocabs:GUIActionNameVocab-1.0",
				 "parameter_associated_objects" : {"WindowName" : {"associated_object_type" : "GUIWindowObjectType",
				 												   "associated_object_element" : "Window_Display_Name",
				 												   "association_type" : "input"}}},
"FindWindowW" : {"action_name" : "find window",
				 "action_vocab" : "maecVocabs:GUIActionNameVocab-1.0",
				 "parameter_associated_objects" : {"WindowName" : {"associated_object_type" : "GUIWindowObjectType",
				 												   "associated_object_element" : "Window_Display_Name",
				 												   "association_type" : "input"}}},
"FindWindowExA" : {"action_name" : "find window",
				   "action_vocab" : "maecVocabs:GUIActionNameVocab-1.0",
				   "parameter_associated_objects" : {"WindowName" : {"associated_object_type" : "GUIWindowObjectType",
				 												   	 "associated_object_element" : "Window_Display_Name",
				 												   	 "association_type" : "input"}}},
"FindWindowExW" : {"action_name" : "find window",
				   "action_vocab" : "maecVocabs:GUIActionNameVocab-1.0",
				   "parameter_associated_objects" : {"WindowName" : {"associated_object_type" : "GUIWindowObjectType",
				 												   	 "associated_object_element" : "Window_Display_Name",
				 												   	 "association_type" : "input"}}},
"SetWindowsHookExA" : {"action_name" : "add windows hook",
				               "action_vocab" : "maecVocabs:HookingActionNameVocab-1.0",
				               "parameter_associated_objects" : {"HookIdentifier" : {"associated_object_type" : "WindowsKernelHookObjectType",
				 												   	                                         "associated_object_element" : "Hook_Description",
				 												   	                                         "association_type" : "input"},
                                                         "ProcedureAddress" : {"associated_object_type" : "WindowsKernelHookObjectType",
				 												   	                                           "associated_object_element" : "Hooking_Address",
				 												   	                                           "association_type" : "input"},
                                                         "ThreadId" : {"associated_object_type" : "WindowsThreadObjectType",
				 												   	                                   "associated_object_element" : "Thread_ID",
				 												   	                                   "association_type" : "input"}}},
"SetWindowsHookExW" : {"action_name" : "add windows hook",
				               "action_vocab" : "maecVocabs:HookingActionNameVocab-1.0",
				               "parameter_associated_objects" : {"HookIdentifier" : {"associated_object_type" : "WindowsKernelHookObjectType",
				 												   	                                         "associated_object_element" : "Hook_Description",
				 												   	                                         "association_type" : "input"},
                                                         "ProcedureAddress" : {"associated_object_type" : "WindowsKernelHookObjectType",
				 												   	                                           "associated_object_element" : "Hooking_Address",
				 												   	                                           "association_type" : "input"},
                                                         "ThreadId" : {"associated_object_type" : "WindowsThreadObjectType",
				 												   	                                   "associated_object_element" : "Thread_ID",
				 												   	                                   "association_type" : "input"}}},
"UnhookWindowsHookEx" : {"action_name" : "remove windows hook",
				                 "parameter_associated_objects" : {"HookHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				 												   	                                       "associated_object_element" : "ID",
				 												   	                                       "association_type" : "input"}}},                                       
"LdrLoadDll" : {"action_name" : "load library",
				        "action_vocab" : "maecVocabs:LibraryActionNameVocab-1.0",
				        "parameter_associated_objects" : {"FileName" : {"associated_object_type" : "LibraryObjectType",
				 												   	                            "associated_object_element" : "Name",
				 												   	                            "association_type" : "input"},
                                                  "BaseAddress" : {"associated_object_type" : "LibraryObjectType",
				 												   	                               "associated_object_element" : "Base_Address",
				 												   	                               "association_type" : "output"}}},
"LdrGetDllHandle" : {"action_name" : "get dll handle",
				             "parameter_associated_objects" : {"FileName" : {"associated_object_type" : "LibraryObjectType",
				 												   	                                 "associated_object_element" : "Name",
				 												   	                                 "association_type" : "input"},
                                                       "ModuleHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				 												   	                                     "associated_object_element" : "ID",
				 												   	                                     "association_type" : "output"}}},
"LdrGetProcedureAddress" : {"action_name" : "get function address",
                            "action_vocab" : "maecVocabs:LibraryActionNameVocab-1.0",
				            "parameter_associated_objects" : {"ModuleHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				 												   	            "associated_object_element" : "ID",
				 												   	            "association_type" : "input"},
                                                               "group_together_nested" : {"parameter_mappings" : [{"parameter_name" : "FunctionName", "element_name" : "Function_Name"}, 
                                                                                                                    {"parameter_name" : "Ordinal", "element_name" : "Ordinal"}],
                                                                                            "associated_object_type" : "WindowsExecutableFileObjectType",
                                                                                            "associated_object_element" : "Exports/Exported_Functions/list__",
                                                                                            "association_type" : "input"}}},
"DeviceIoControl" : {"action_name" : "send control code to driver",
				             "parameter_associated_objects" : {"FileName" : {"associated_object_type" : "LibraryObjectType",
				 												   	                                 "associated_object_element" : "Path",
				 												   	                                 "association_type" : "input"}},
                     "parameter_associated_arguments" : {"IoControlCode" : {"associated_argument_name" : "Control Code",
				 												   	                                       "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},
"ExitWindowsEx" : {"action_name" : "shutdown system",
                   "action_vocab" : "maecVocabs:SystemActionNameVocab-1.0",
                   "parameter_associated_arguments" : {"Flags" : {"associated_argument_name" : "Flags"},
                                                       "Reason" : {"associated_argument_name" : "Reason"}}},
"IsDebuggerPresent" : {"action_name" : "check for remote debugger",
                       "action_vocab" : "maecVocabs:DebuggingActionNameVocab-1.0"},
"LookupPrivilegeValueW" : {"action_name" : "find privilege value",
                           "parameter_associated_objects" : {"SystemName" : {"associated_object_type" : "SystemObjectType",
				 												   	                                         "associated_object_element" : "Hostname",
				 												   	                                         "association_type" : "input"}},
                           "parameter_associated_arguments" : {"PrivilegeName" : {"associated_argument_name" : "Privilege Name"}}},
"NtClose" : {"action_name" : "close handle",
                             "parameter_associated_objects" : {"Handle" : {"associated_object_type" : "WindowsHandleObjectType",
				 												   	                                       "associated_object_element" : "ID",
				 												   	                                       "association_type" : "input"}}},
"WriteConsoleA" : {"action_name" : "write to console",
                   "parameter_associated_objects" : {"ConsoleHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				 												   	                                    "associated_object_element" : "ID",
				 												   	                                    "association_type" : "input"}}},
"WriteConsoleW" : {"action_name" : "write to console",
                   "parameter_associated_objects" : {"ConsoleHandle" : {"associated_object_type" : "WindowsHandleObjectType",
				 												   	                                    "associated_object_element" : "ID",
				 												   	                                    "association_type" : "input"}}},
"NtDelayExecution" : {"action_name" : "delay execution",
					  "parameter_associated_arguments" : {"Milliseconds" : {"associated_argument_name" : "Milliseconds"}}},					  
"GetLocalTime" : {"action_name" : "get system local time",
				  "action_vocab" : "maecVocabs:SystemActionNameVocab-1.0"},
"GetSystemTime" : {"action_name" : "get system time",
				   "action_vocab" : "maecVocabs:SystemActionNameVocab-1.0"},				   
"GetTickCount" : {"action_name" : "get tick count"},
"NtQuerySystemTime" : {"action_name" : "get system time",
					   "action_vocab" : "maecVocabs:SystemActionNameVocab-1.0"},
"WSAStartup" : {"action_name" : "initialize winsock",
				"parameter_associated_arguments" : {"VersionRequested" : {"associated_argument_name" : "Version Requested"}}},
"NtCreateMutant" : {"action_name" : "create mutex",
					"action_vocab" : "maecVocabs:SynchronizationActionNameVocab-1.0",
					"parameter_associated_objects" : {"Handle" : {"associated_object_type" : "WindowsHandleObjectType",
																  "associated_object_element" : "ID",
																  "association_type" : "output"},
                                                      "MutexName" : {"associated_object_type" : "WindowsMutexObjectType",
																     "associated_object_element" : "Name",
																     "association_type" : "output"}},
					"parameter_associated_arguments" : {"InitialOwner" : {"associated_argument_name" : "Initial Owner"}}},
"NtOpenMutant" : {"action_name" : "open mutex",
				  "action_vocab" : "maecVocabs:SynchronizationActionNameVocab-1.0",
				  "parameter_associated_objects" : {"Handle" : {"associated_object_type" : "WindowsHandleObjectType",
																"associated_object_element" : "ID",
																"association_type" : "output"},
                                                    "MutexName" : {"associated_object_type" : "WindowsMutexObjectType",
																   "associated_object_element" : "Name",
																   "association_type" : "input"}}},
"OpenSCManagerA" : {"action_name" : "open service control manager",
                    "parameter_associated_objects" : {"MachineName" : {"associated_object_type" : "SystemObjectType",
				 												   	   "associated_object_element" : "Hostname",
				 												   	   "association_type" : "input"}},
                    "parameter_associated_arguments" : {"DesiredAccess" : {"associated_argument_name" : "Access Mode", 
                                                                           "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
                                                        "DatabaseName" : {"associated_argument_name" : "Database Name"}}},
"OpenSCManagerW" : {"action_name" : "open service control manager",
                    "parameter_associated_objects" : {"MachineName" : {"associated_object_type" : "SystemObjectType",
				 												   	   "associated_object_element" : "Hostname",
				 												   	   "association_type" : "input"}},
                    "parameter_associated_arguments" : {"DesiredAccess" : {"associated_argument_name" : "Access Mode", 
                                                                           "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
                                                        "DatabaseName" : {"associated_argument_name" : "Database Name"}}},
"CreateServiceA" : {"action_name" : "create service",
					"action_vocab" : "maecVocabs:ServiceActionNameVocab-1.0",
					"parameter_associated_objects" : {"ServiceControlHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																                "associated_object_element" : "ID",
																                "association_type" : "input"},
                                                      "ServiceName" : {"associated_object_type" : "WindowsServiceObjectType",
																       "associated_object_element" : "Service_Name",
																       "association_type" : "output"},
                                                      "DisplayName" : {"associated_object_type" : "WindowsServiceObjectType",
																       "associated_object_element" : "Display_Name",
																       "association_type" : "output"},
                                                      "ServiceType" : {"associated_object_type" : "WindowsServiceObjectType",
																       "associated_object_element" : "Service_Type",
																       "association_type" : "output"},
                                                      "StartType" : {"associated_object_type" : "WindowsServiceObjectType",
																     "associated_object_element" : "Startup_Type",
																     "association_type" : "output"},
                                                      "ServiceStartName" : {"associated_object_type" : "WindowsServiceObjectType",
																            "associated_object_element" : "Started_As",
																            "association_type" : "output"},
                                                      "BinaryPathName" : {"associated_object_type" : "WindowsServiceObjectType",
																          "associated_object_element" : "Image_Info/Path",
																          "association_type" : "output"},
                                                      "group_together" : ["ServiceName", "DisplayName", "ServiceType", 
                                                                          "StartType", "ServiceStartName", "BinaryPathName"]},
                    "parameter_associated_arguments" : {"DesiredAccess" : {"associated_argument_name" : "Access Mode", 
                                                                           "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
                                                        "ErrorControl" : {"associated_argument_name" : "Error Control"}}},
"CreateServiceW" : {"action_name" : "create service",
					"action_vocab" : "maecVocabs:ServiceActionNameVocab-1.0",
					"parameter_associated_objects" : {"ServiceControlHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																                "associated_object_element" : "ID",
																                "association_type" : "input"},
                                                      "ServiceName" : {"associated_object_type" : "WindowsServiceObjectType",
																       "associated_object_element" : "Service_Name",
																       "association_type" : "output"},
                                                      "DisplayName" : {"associated_object_type" : "WindowsServiceObjectType",
																       "associated_object_element" : "Display_Name",
																       "association_type" : "output"},
                                                      "ServiceType" : {"associated_object_type" : "WindowsServiceObjectType",
																       "associated_object_element" : "Service_Type",
																       "association_type" : "output"},
                                                      "StartType" : {"associated_object_type" : "WindowsServiceObjectType",
																     "associated_object_element" : "Startup_Type",
																     "association_type" : "output"},
                                                      "ServiceStartName" : {"associated_object_type" : "WindowsServiceObjectType",
																            "associated_object_element" : "Started_As",
																            "association_type" : "output"},
                                                      "BinaryPathName" : {"associated_object_type" : "WindowsServiceObjectType",
																          "associated_object_element" : "Image_Info/Path",
																          "association_type" : "output"},
                                                      "group_together" : ["ServiceName", "DisplayName", "ServiceType", 
                                                                          "StartType", "ServiceStartName", "BinaryPathName"]},
                    "parameter_associated_arguments" : {"DesiredAccess" : {"associated_argument_name" : "Access Mode", 
                                                                           "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
                                                        "ErrorControl" : {"associated_argument_name" : "Error Control"}}},
"OpenServiceA" : {"action_name" : "open service",
				  "action_vocab" : "maecVocabs:ServiceActionNameVocab-1.0",
				  "parameter_associated_objects" : {"ServiceControlManager" : {"associated_object_type" : "WindowsHandleObjectType",
																                "associated_object_element" : "ID",
																                "association_type" : "input"},
                                                     "ServiceName" : {"associated_object_type" : "WindowsServiceObjectType",
																       "associated_object_element" : "Service_Name",
																       "association_type" : "input"}},
                    "parameter_associated_arguments" : {"DesiredAccess" : {"associated_argument_name" : "Access Mode", 
                                                                           "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},
"OpenServiceW" : {"action_name" : "open service",
				  "action_vocab" : "maecVocabs:ServiceActionNameVocab-1.0",
				  "parameter_associated_objects" : {"ServiceControlManager" : {"associated_object_type" : "WindowsHandleObjectType",
																                "associated_object_element" : "ID",
																                "association_type" : "input"},
                                                     "ServiceName" : {"associated_object_type" : "WindowsServiceObjectType",
																       "associated_object_element" : "Service_Name",
																       "association_type" : "input"}},
                    "parameter_associated_arguments" : {"DesiredAccess" : {"associated_argument_name" : "Access Mode", 
                                                                           "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},
"StartServiceA" : {"action_name" : "start service",
				   "action_vocab" : "maecVocabs:ServiceActionNameVocab-1.0",
				   "parameter_associated_objects" : {"ServiceHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																       "associated_object_element" : "ID",
																       "association_type" : "input"}},
                   "parameter_associated_arguments" : {"Arguments" : {"associated_argument_name" : "Access Mode"}}},
"StartServiceW" : {"action_name" : "start service",
				   "action_vocab" : "maecVocabs:ServiceActionNameVocab-1.0",
				   "parameter_associated_objects" : {"ServiceHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																       "associated_object_element" : "ID",
																       "association_type" : "input"}},
                   "parameter_associated_arguments" : {"Arguments" : {"associated_argument_name" : "Access Mode"}}},
"ControlService" : {"action_name" : "send control code to service",
				   "action_vocab" : "maecVocabs:ServiceActionNameVocab-1.0",
				   "parameter_associated_objects" : {"ServiceHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																       "associated_object_element" : "ID",
																       "association_type" : "input"}},
                   "parameter_associated_arguments" : {"ControlCode" : {"associated_argument_name" : "Control Mode",
                                                                        "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},
"DeleteService" : {"action_name" : "delete service",
				   "action_vocab" : "maecVocabs:ServiceActionNameVocab-1.0",
				   "parameter_associated_objects" : {"ServiceHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																       "associated_object_element" : "ID",
																       "association_type" : "input"}}},
"NtCreateThread" : {"action_name" : "create thread",
					"action_vocab" : "maecVocabs:ProcessThreadActionNameVocab-1.0",
					"parameter_associated_objects" : {"ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																	 	"associated_object_element" : "ID",
																	 	"association_type" : "output"},
													  "ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																		 "associated_object_element" : "ID",
																		 "association_type" : "input"}},
					"parameter_associated_arguments" : {"ObjectAttributes" : {"associated_argument_name" : "Options", 
																		   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},
				
"NtOpenThread" : {"action_name" : "open thread",
				  "parameter_associated_objects" : {"ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																	  "associated_object_element" : "ID",
																	  "association_type" : "output"}},
					"parameter_associated_arguments" : {"DesiredAccess" : {"associated_argument_name" : "Access Mode", 
																		   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
													    "ObjectAttributes" : {"associated_argument_name" : "Options",
																			  "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},

"NtGetContextThread" : {"action_name" : "get thread context",
						"action_vocab" : "maecVocabs:ProcessThreadActionNameVocab-1.0",
						"parameter_associated_objects" : {"ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																		    "associated_object_element" : "ID",
																		    "association_type" : "input"}}},

"NtSetContextThread" : {"action_name" : "set thread context",
						"action_vocab" : "maecVocabs:ProcessThreadActionNameVocab-1.0",
						"parameter_associated_objects" : {"ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																		    "associated_object_element" : "ID",
																		    "association_type" : "input"}}},

"NtSuspendThread" : {"action_name" : "suspend thread",
			         "parameter_associated_objects" : {"ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																		    "associated_object_element" : "ID",
																		    "association_type" : "input"}}},
"NtResumeThread" : {"action_name" : "resume thread",
				    "parameter_associated_objects" : {"ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																		    "associated_object_element" : "ID",
																		    "association_type" : "input"}}},

"NtTerminateThread" : {"action_name" : "kill thread",
					   "action_vocab" : "maecVocabs:ProcessThreadActionNameVocab-1.0",
					   "parameter_associated_objects" : {"ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																		    "associated_object_element" : "ID",
																		    "association_type" : "input"}}},

"CreateThread" : {"action_name" : "create thread",
				  "action_vocab" : "maecVocabs:ProcessThreadActionNameVocab-1.0",
				  "parameter_associated_objects" : {"ThreadId" : {"associated_object_type" : "WindowsThreadObjectType",
																  "associated_object_element" : "Thread_ID",
																  "association_type" : "output"}},
					"parameter_associated_arguments" : {"StartRoutine" : {"associated_argument_name" : "Code Address", 
																		   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
														"Parameter" : {"associated_argument_name" : "Options",
																	   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
														"CreationFlags" : {"associated_argument_name" : "Creation Flags",
																		   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},

"CreateRemoteThread" : {"action_name" : "create remote thread in process",
						"action_vocab" : "maecVocabs:ProcessThreadActionNameVocab-1.0",
						"parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																			 "associated_object_element" : "ID",
																			 "association_type" : "input"},
														  "ThreadId" : {"associated_object_type" : "WindowsThreadObjectType",
																	    "associated_object_element" : "Thread_ID",
																	    "association_type" : "output"}},
						"parameter_associated_arguments" : {"StartRoutine" : {"associated_argument_name" : "Code Address", 
																		   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
														"Parameter" : {"associated_argument_name" : "Options",
																	   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
														"CreationFlags" : {"associated_argument_name" : "Creation Flags",
																		   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},
"ExitThread" : {"action_name" : "exit thread"},				
"RtlCreateUserThread" : {"action_name" : "create thread",
				  		 "action_vocab" : "maecVocabs:ProcessThreadActionNameVocab-1.0",
				  		 "parameter_associated_objects" : {"ProcessHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																			  "associated_object_element" : "ID",
																			  "association_type" : "input"},
														   "ThreadHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																			 "associated_object_element" : "ID",
																			 "association_type" : "output"},
														   "ThreadId" : {"associated_object_type" : "WindowsThreadObjectType",
														   				 "associated_object_element" : "Thread_ID",
														   				 "association_type" : "output"}},
						 "parameter_associated_arguments" : {"CreatedSuspended" : {"associated_argument_name" : "Control Parameter",
																				   "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
															 "StartAddress" : {"associated_argument_name" : "Code Address", 
																		       "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
															 "StartParameter" : {"associated_argument_name" : "Options",
																	   	    "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"}}},
"URLDownloadToFileW" : {"action_name" : "download file",
				        "action_vocab" : "maecVocabs:NetworkActionNameVocab-1.0",
				        "parameter_associated_objects" : {"URL" : {"associated_object_type" : "URIObjectType",
																   "associated_object_element" : "Value",
																    "association_type" : "input"},
                                                          "FileName" : {"associated_object_type" : "FileObjectType",
												   				        "associated_object_element" : "File_Path",
												   				        "association_type" : "output"}}},
"InternetOpenA" : {"action_name" : "initialize wininet",
				   "parameter_associated_objects" : {"Agent" : {"associated_object_type" : "HTTPSessionObjectType",
																"associated_object_element" : "list__HTTP_Request_Response/HTTP_Client_Request/HTTP_Request_Header/Parsed_Header/User_Agent",
																"association_type" : "input"}},
                   "parameter_associated_arguments" : {"AccessType" : {"associated_argument_name" : "Access Mode",
                                                                        "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
                                                       "ProxyName" : {"associated_argument_name" : "Proxy Name"},
                                                       "ProxyBypass" : {"associated_argument_name" : "Proxy Bypass"},
                                                       "Flags" : {"associated_argument_name" : "Flags"}}}, 
"InternetOpenW" : {"action_name" : "initialize wininet",
				   "parameter_associated_objects" : {"Agent" : {"associated_object_type" : "HTTPSessionObjectType",
																"associated_object_element" : "list__HTTP_Request_Responses/HTTP_Client_Request/HTTP_Request_Header/Parsed_Header/User_Agent",
																"association_type" : "input"}},
                   "parameter_associated_arguments" : {"AccessType" : {"associated_argument_name" : "Access Mode",
                                                                        "associated_argument_vocab" : "cyboxVocabs:ActionArgumentNameVocab-1.0"},
                                                       "ProxyName" : {"associated_argument_name" : "Proxy Name"},
                                                       "ProxyBypass" : {"associated_argument_name" : "Proxy Bypass"},
                                                       "Flags" : {"associated_argument_name" : "Flags"}}},
"InternetConnectA" : {"action_name" : "connect to server",
				      "parameter_associated_objects" : {"InternetHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																            "associated_object_element" : "ID",
																            "association_type" : "input"},
                                                        "ServerName" : {"associated_object_type" : "URIObjectType",
																        "associated_object_element" : "Value",
																        "association_type" : "input"},
                                                        "ServerPort" : {"associated_object_type" : "PortObjectType",
																        "associated_object_element" : "Port_Value",
																        "association_type" : "input"}},
                      "parameter_associated_arguments" : {"Username" : {"associated_argument_name" : "Username"},
                                                          "Password" : {"associated_argument_name" : "Password"},
                                                          "Service" : {"associated_argument_name" : "Service Type"},
                                                          "Flags" : {"associated_argument_name" : "Flags"}}},
"InternetConnectW" : {"action_name" : "connect to server",
				      "parameter_associated_objects" : {"InternetHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																            "associated_object_element" : "ID",
																            "association_type" : "input"},
                                                        "ServerName" : {"associated_object_type" : "URIObjectType",
																        "associated_object_element" : "Value",
																        "association_type" : "input"},
                                                        "ServerPort" : {"associated_object_type" : "PortObjectType",
																        "associated_object_element" : "Port_Value",
																        "association_type" : "input"}},
                      "parameter_associated_arguments" : {"Username" : {"associated_argument_name" : "Username"},
                                                          "Password" : {"associated_argument_name" : "Password"},
                                                          "Service" : {"associated_argument_name" : "Service Type"},
                                                          "Flags" : {"associated_argument_name" : "Flags"}}},
"InternetOpenURLA" : {"action_name" : "connect to url",
                      "action_vocab" : "maecVocabs:NetworkActionNameVocab-1.0",
				      "parameter_associated_objects" : {"ConnectionHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																              "associated_object_element" : "ID",
																              "association_type" : "input"},
                                                        "URL" : {"associated_object_type" : "URIObjectType",
																 "associated_object_element" : "Value",
																 "association_type" : "input"},
                                                        "Headers" : {"associated_object_type" : "HTTPSessionObjectType",
																     "associated_object_element" : "list__HTTP_Request_Response/HTTP_Client_Request/HTTP_Request_Header/Parsed_Header/Raw_Header",
																     "association_type" : "input"}},
                      "parameter_associated_arguments" : {"Flags" : {"associated_argument_name" : "Flags"}}},
"InternetOpenURLW" : {"action_name" : "connect to url",
                      "action_vocab" : "maecVocabs:NetworkActionNameVocab-1.0",
				      "parameter_associated_objects" : {"ConnectionHandle" : {"associated_object_type" : "WindowsHandleObjectType",
																              "associated_object_element" : "ID",
																              "association_type" : "input"},
                                                        "URL" : {"associated_object_type" : "URIObjectType",
																 "associated_object_element" : "Value",
																 "association_type" : "input"},
                                                        "Headers" : {"associated_object_type" : "HTTPSessionObjectType",
																     "associated_object_element" : "list__HTTP_Request_Response/HTTP_Client_Request/HTTP_Request_Header/Parsed_Header/Raw_Header",
																     "association_type" : "input"}},
                      "parameter_associated_arguments" : {"Flags" : {"associated_argument_name" : "Flags"}}},                                                                                                                                                                                                                                                                                                     
}

def hiveHexToString(hive_hex_value):
    """Maps a Registry Hive hex input to its String (name) equivalent"""
    if str(hive_hex_value) == "0x80000000":
        return "HKEY_CLASSES_ROOT"
    elif str(hive_hex_value) == "0x80000001":
        return "HKEY_CURRENT_USER"
    elif str(hive_hex_value) == "0x80000002":
        return "HKEY_LOCAL_MACHINE"
    elif str(hive_hex_value) == "0x80000003":
        return "HKEY_USERS"
    elif str(hive_hex_value) == "0x80000004":
        return "HKEY_PERFORMANCE_DATA"
    elif str(hive_hex_value) == "0x80000005":
        return "HKEY_CURRENT_CONFIG"
    elif str(hive_hex_value) == "0x80000006":
        return "HKEY_DYN_DATA"
    else:
        return hive_hex_value